In [28]:
import torch
import numpy as np
import pandas as pd
import folium
import pickle
from geomodel import geoModel

In [8]:
_RUN_DATA = "data/runs.pkl"
_MODEL_SAVE = "model_save/model.pt"

## Load all the running data and the model

In [6]:
with open(_RUN_DATA,"rb") as f:
    runs = pickle.load(f)

In [10]:
unique_points = 82
context_size = 3
embedding_dimension = 10
model = geoModel(unique_points+1, embedding_dimension, context_size)
model.load_state_dict(torch.load(_MODEL_SAVE)["model_state_dict"])

Embedding(83, 10)
Linear(in_features=30, out_features=128, bias=True)


<All keys matched successfully>

In [15]:
key = "2016-04-07-19-30-19.csv"

In [17]:
run = runs[key]

In [31]:
features = run["features"]
labels = run["labels"]
predicted = model.predict(torch.from_numpy(features)).numpy()
points = pd.read_csv("data/points.csv")

In [32]:
features, labels, predicted

(array([[26, 70, 37],
        [70, 37, 38],
        [37, 38, 39],
        [38, 39, 40],
        [39, 40, 77],
        [40, 77, 43],
        [77, 43, 42],
        [43, 42, 43],
        [42, 43, 77],
        [43, 77, 41],
        [77, 41, 38],
        [41, 38, 37],
        [38, 37, 36],
        [37, 36, 71],
        [36, 71, 25],
        [71, 25, 27],
        [25, 27, 78],
        [27, 78, 64],
        [78, 64, 67]]),
 array([38, 39, 40, 77, 43, 42, 43, 77, 41, 38, 37, 36, 71, 25, 27, 78, 64,
        67, 74]),
 array([38, 41, 40, 41, 43, 42, 43, 77, 41, 38, 37, 70, 71, 25, 72, 78, 64,
        66, 74]))